import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">SignIn</Link>
        </li>
        <li>
          <Link to="/signuppage">SignUpPage</Link>
        </li>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/searchpage">SearchPage</Link>
        </li>
        <li>
          <Link to="/bookdetails">BookDetails</Link>
        </li>
        <li>
          <Link to="/mybooks">MyBooks</Link>
        </li>
        <li>
          <Link to="/wishlist">Wishlist</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
